[shell]
program = "fish"
# [colors]
# draw_bold_text_with_bright_colors = true

[font]
size = 9

[font.bold]
style = "Bold"
family = "Monaspace Radon"

[font.bold_italic]
style = "Bold Italic"
family = "Monaspace Radon"

[font.italic]
style = "Italic"
family = "Monaspace Radon"

[font.normal]
style = "Regular"
family = "Monaspace Radon"


[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5

[colors.primary]
# background = "0x282828"
foreground = "0xeeeeee"

[colors.normal]
black = "0x282828"
red = "0xf43753"
green = "0xc9d05c"
yellow = "0xffc24b"
blue = "0xb3deef"
magenta = "0xd3b987"
cyan = "0x73cef4"
white = "0xeeeeee"

[colors.bright]
black = "0x4c4c4c"
red = "0xf43753"
green = "0xc9d05c"
yellow = "0xffc24b"
blue = "0xb3deef"
magenta = "0xd3b987"
cyan = "0x73cef4"
white = "0xfeffff"
